name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        run: uv run pytest

      - name: Update coverage badge (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          uv run python update_coverage_badge.py

      - name: Create PR for coverage badge update (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');

            // Check if README.md has changes
            try {
              execSync('git diff --quiet README.md');
              console.log('No changes to coverage badge, skipping PR creation');
              return;
            } catch (error) {
              console.log('Coverage badge changes detected, creating PR...');
            }

            // Configure git
            execSync('git config --local user.email "action@github.com"');
            execSync('git config --local user.name "GitHub Action"');

            // Create a unique branch name
            const timestamp = Date.now();
            const branchName = `update-coverage-badge-${timestamp}`;

            // Create and checkout new branch
            execSync(`git checkout -b ${branchName}`);

            // Add and commit changes
            execSync('git add README.md');
            execSync('git commit -m "chore: update coverage badge [skip ci]"');

            // Push the branch
            execSync(`git push origin ${branchName}`);

            // Close any existing open coverage badge PRs first
            const { data: existingPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main'
            });

            const coveragePRs = existingPRs.filter(pr =>
              pr.title.includes('update coverage badge') ||
              pr.head.ref.includes('update-coverage-badge')
            );

            for (const pr of coveragePRs) {
              console.log(`Closing outdated coverage PR #${pr.number}`);
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });

              // Delete the branch
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${pr.head.ref}`
                });
              } catch (e) {
                console.log(`Could not delete branch ${pr.head.ref}: ${e.message}`);
              }
            }

            // Create new PR
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'chore: update coverage badge',
              head: branchName,
              base: 'main',
              body: `## 🤖 Automated Coverage Badge Update

            This PR automatically updates the coverage badge in the README.md file based on the latest test coverage results.

            ### Changes
            - Updated coverage badge to reflect current test coverage percentage

            ### Notes
            - This PR was automatically created by the GitHub Actions workflow
            - The coverage badge will be updated when this PR is merged to main
            - This is a routine maintenance update with no functional changes

            **Auto-generated by GitHub Actions** 🚀`
            });

            console.log(`Created PR #${pr.number}: ${pr.html_url}`);

      - name: Generate coverage summary for PR
        if: github.event_name == 'pull_request'
        id: coverage
        run: |
          # Get coverage percentage
          COVERAGE=$(python -c "
          import json
          with open('coverage.json') as f:
              data = json.load(f)
          print(int(data['totals']['percent_covered']))
          ")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

          # Get coverage details
          python -c "
          import json
          with open('coverage.json') as f:
              data = json.load(f)

          print('## 📊 Test Coverage Report')
          print()

          total = data['totals']
          percentage = int(total['percent_covered'])

          # Color coding
          if percentage >= 90:
              emoji = '🟢'
          elif percentage >= 80:
              emoji = '🟡'
          elif percentage >= 70:
              emoji = '🟡'
          elif percentage >= 60:
              emoji = '🟠'
          elif percentage >= 50:
              emoji = '🟠'
          else:
              emoji = '🔴'

          print(f'**Current Coverage: {emoji} {percentage}%**')
          print()
          print('| Metric | Value |')
          print('|--------|-------|')
          print(f'| Total Lines | {total[\"num_statements\"]} |')
          print(f'| Covered Lines | {total[\"covered_lines\"]} |')
          print(f'| Missing Lines | {total[\"missing_lines\"]} |')
          print(f'| Coverage | {percentage}% |')
          print()
          print('### Files with Low Coverage')
          print('| File | Coverage | Missing Lines |')
          print('|------|----------|---------------|')

          low_coverage_files = []
          for filename, file_data in data['files'].items():
              if ('test_' not in filename and
                  '__pycache__' not in filename and
                  '.egg-info' not in filename and
                  file_data['summary']['percent_covered'] < 80):

                  coverage_pct = int(file_data['summary']['percent_covered'])
                  missing = file_data['summary']['missing_lines']
                  low_coverage_files.append((filename, coverage_pct, missing))

          if low_coverage_files:
              for filename, coverage_pct, missing in sorted(low_coverage_files, key=lambda x: x[1]):
                  print(f'| {filename} | {coverage_pct}% | {missing} |')
          else:
              print('| *No files with coverage < 80%* | - | - |')

          print()
          print('> 💡 Coverage badge will be automatically updated when this PR is merged to main.')
          " > coverage_summary.md

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverageSummary = fs.readFileSync('coverage_summary.md', 'utf8');

            // Find existing coverage comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.find(comment =>
              comment.body.includes('📊 Test Coverage Report') &&
              comment.user.login === 'github-actions[bot]'
            );

            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: coverageSummary
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: coverageSummary
              });
            }
